/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "immxdydtxmdhgaxagryl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbXhkeWR0eG1kaGdheGFncnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODIxMTQsImV4cCI6MjA3NzE1ODExNH0.4O-mP2QBheStsOUUOdEDrKFPiXOIL-JaNdIs1fevPx8"